#!/bin/bash
#
# monitor-runlevelagent starts the RunlevelAgent in production mode.
#
# Load before nm, vcached, and vservers, vserver-reference
# chkconfig: 3 14 85
# description: Start RunlevelAgent to report the current Runlevel to PLC at
# 		periodic intervals.
#
# Stephen Soltesz <soltesz@cs.princeton.edu>
# Copyright (C) 2008 The Trustees of Princeton University
#
# $Id$
#

case "$1" in
    start|restart|reload)

		start_rla

	;;
    stop|status)
	exit 0
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac

function start_rla ()
{
	RLA=/usr/bin/RunlevelAgent.py
	$RLA &> /var/log/rla.log &
}
