#!/bin/bash
#
# monitor-runlevelagent starts the RunlevelAgent in production mode.
#
# Load before nm, vcached, and vservers, vserver-reference
# chkconfig: 3 14 85
# description: Start RunlevelAgent to report the current Runlevel to PLC at
# 		periodic intervals.
#
# Stephen Soltesz <soltesz@cs.princeton.edu>
# Copyright (C) 2008 The Trustees of Princeton University
#
# $Id$
#

function start_rla ()
{
	args=$1
	ret=$( pgrep -f -l RunlevelAgent )
	if [[ -z $ret ]] ; then
	    echo "Starting RunlevelAgent"
		if [[ -f RunlevelAgent.py ]] ; then 
			RLA="/usr/bin/python ./RunlevelAgent.py"
		else
			RLA=/usr/bin/RunlevelAgent.py
		fi
		$RLA $args > /var/log/rla.log 2>&1 &
	fi
}

case "$1" in
    start|restart|reload)

		start_rla $2

	;;
    stop|status)
		pkill -f RunlevelAgent
		exit 0
	;;
    *)
		echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac

